version: "3.1"
services:
  php-fpm:
    image: php:7.4-fpm-alpine
    volumes:
      - $PWD/src:/var/www/html
  nginx:
    image: nginx:1.19-alpine
    depends_on:
      - php-fpm
    ports:
      - 8888:80
    volumes:
      - $PWD/config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - $PWD/src:/var/www/html
  db:
    image: mariadb:10.5-focal
    ports:
      - 3333:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - $PWD/db/data:/var/lib/mysql